#!/usr/bin/env bash
#This script will display lines containing the bash word, thus allowing you to easily get the PID of your Bash process

#shellcheck disable=SC2009

#ps -e | grep bash | awk '{print $1}'
