#!/usr/bin/env bash
# Prints some fields of the /etc/passwd file
file_name="/etc/passwd"
j=0
lines=0
IFS=':'
if test -f $file_name; then
  lines="$(wc -l < $file_name)"
  fields=('username' 'password' 'user_id' 'group_id' 'user_id_info' 'home_dir' 'command')
  while [[ $i -lt $lines ]]; do
    j="$((j + 1))"
    read -r -a fields < <(tail -n 1 <(head -n $j < $file_name))
    echo "${fields[0]}:${fields[2]}:${fields[5]}"
  done
fi
