#!/usr/bin/env bash
# Prints a story about the contents of the /etc/passwd file
file_name="/etc/passwd"
j=0
lines=0
IFS=':'
if test -f $file_name; then
  lines="$(wc -l < $file_name)"
  fields=('username' 'password' 'user_id' 'group_id' 'user_id_info' 'home_dir' 'command')
  while [[ $j -lt $lines ]]; do
    j="$((j + 1))"
    read -r -a fields < <(tail -n 1 <(head -n $j < $file_name))
    echo "The user ${fields[0]} is part of the ${fields[3]} gang, lives in ${fields[5]} and \
rides ${fields[6]}. ${fields[2]}'s place is protected by the passcode ${fields[1]}, more \
info about the user here: ${fields[4]}"
  done
fi
