#!/usr/bin/env bash
# Prints the numbers from 1 to 20 inclusive
j=0
while [[ $j -lt 20 ]]; do
  case "$j" in
    "3")
      echo -e "4\nbad luck from China"
      ;;  
    "8")
      echo -e "9\nbad luck from Japan"
      ;;  
    "16")
      echo -e "17\nbad luck from Italy"
      ;;  
    *)  
    echo "$((j + 1))"
  esac
  j="$((j + 1))"
done
