#!/usr/bin/env bash
# Dislay the name of the contents of the current directory
# after the first "-" character
files=()
readarray -t files < <(find . -regex "./[^.].*" | sort)
for ((y = 0; y < "${#files[@]}"; y++)) do
  z=0 
  file_printed="0"
  for ((z = 0; z < "${#files[i]}"; z++)) do
    if [[ "${files[y]:z:1}" == "-" ]]; then
      echo "${files[y]:z+1}"
      file_printed="1"
      break
    fi  
  done
  if [[ $file_printed == "0" ]]; then
    echo "${files[i]:2}"
  fi  
done
